-- AlterTable
ALTER TABLE "Category" ADD COLUMN     "allowTimeRange" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "color" TEXT NOT NULL DEFAULT '#2196F3',
ADD COLUMN     "defaultToCurrentDate" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "hasContent" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "hasDate" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "hasPhotos" BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE "Entry" ADD COLUMN     "endDate" TIMESTAMP(3),
ADD COLUMN     "isAllDay" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "startDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "content" DROP NOT NULL;
